sudo: required
services:
- docker
script:
- docker pull dxjoke/tectonic-docker
- docker run --mount src=$TRAVIS_BUILD_DIR,target=/usr/src/tex,type=bind dxjoke/tectonic-docker
  /bin/sh -c "tectonic --keep-intermediates --reruns 0 reports/DC1.tex; tectonic bachproef/DC1.tex"
- docker run --mount src=$TRAVIS_BUILD_DIR,target=/usr/src/tex,type=bind dxjoke/tectonic-docker
  /bin/sh -c "tectonic --keep-intermediates --reruns 0 reports/DC2.tex; tectonic reports/DC2.tex"
- docker run --mount src=$TRAVIS_BUILD_DIR,target=/usr/src/tex,type=bind dxjoke/tectonic-docker
  /bin/sh -c "tectonic --keep-intermediates --reruns 0 reports/SQL.tex; tectonic reports/SQL.tex"
- docker run --mount src=$TRAVIS_BUILD_DIR,target=/usr/src/tex,type=bind dxjoke/tectonic-docker
  /bin/sh -c "tectonic --keep-intermediates --reruns 0 reports/SCCM.tex; tectonic
  reports/SCCM.tex"
- docker run --mount src=$TRAVIS_BUILD_DIR,target=/usr/src/tex,type=bind dxjoke/tectonic-docker
  /bin/sh -c "tectonic --keep-intermediates --reruns 0 reports/Exchange.tex; tectonic
  reports/Exchange.tex"
deploy:
  provider: releases
  api_key:
    secure: SzGT4g8pRZk1N4GiUxJBu6KuGeEIztabCkPIqgDzdc0lxH8N54hhofoyMLu9vaIVnWMRKmGr0fQNEbtBErBdtPaWD+kd94j1gyTO0UCz+oZq6yph++Bl4iltvab7RsUwlXj9yqQGkhGggr+nKgx220NEsohjUjuKawu2DBqsjdaYOOEIjxp0jR1PPYnERpaVqT7xjhUnnE+dc0GimvCCdeJEd4lR0stCi8sLbmryngBa9fwz+Zu5Dr1631HI6kA2At2+SOwp21YIV50+dZheErdVfvXHBWpFDhC9XSmiG51EQId7sgwHVHpFADKmsDsvgeqsvy8Mt+oviZgwmdub55gdNGh4utL3wmlUwJ/uGqxoShmlIsNcV0V8GdrhvFx3HW4TczxVTz4oyUV/ZpYaGumLMK4JpBntUWPP/gDSJQw3x42vLs7Oeda1kkmYqG5Bb1iDy12+jeBUIzMJ61tiWM9NE1YXg3XIyVQl+ZA+FxLdqc3hPtetxrsLc3NoANLtQsg/uOYrL3pVHQvxIsgja/rQmEOQKsiTvqjVOYa06NdiwHYbijzh/1oII9nqIyPUprW9UPfF8dDIWlk8jT3UJ8HHpVLZhvSAymJ7gsfA0ivtHOAAhE8INVZWrFW69Mhe1IFseJ+WcU5+q+fOhwwfWqO+kwrr+OEwPvQtrcypnIQ=
  file:
    - "reports/DC1.pdf"
    - "reports/DC2.pdf"
    - "reports/SQL.pdf"
    - "reports/SCCM.pdf"
    - "reports/Exchange.pdf"
  skip_cleanup: true
  on:
    repo: jensdufour/wsrv-1819-jensdufourhogent